package refusalscan

// HostedResumeCoverageRow binds an exact refusal site to its public API test.
// BuildPlan intentionally keeps native semantics; hosted consumers call these
// separate exec-free entry points before constructing or renewing a process.
type HostedResumeCoverageRow struct {
	Site       Site
	TestName   string
	EntryPoint string
}

// HostedResumeCoverage is a pinned census, not a generated-at-test exemption.
func HostedResumeCoverage() []HostedResumeCoverageRow {
	return []HostedResumeCoverageRow{
		{Site: Site{File: "resume.go", Function: "ElevateResumeIntent", Guard: "if !ok", Return: "return ResumeElevation{}, &ResumeInvalidError{Reason: \"unknown provider\"}", Occurrence: 0}, TestName: "TestResumeElevationRefusals", EntryPoint: "ElevateResumeIntent"},
		{Site: Site{File: "resume.go", Function: "ElevateResumeIntent", Guard: "if !ok", Return: "return ResumeElevation{}, &ResumeInvalidError{Reason: \"provider has no resume grammar\"}", Occurrence: 0}, TestName: "TestResumeElevationRefusals", EntryPoint: "ElevateResumeIntent"},
		{Site: Site{File: "resume.go", Function: "ElevateResumeIntent", Guard: "unconditional", Return: "return elevator.ElevateResumeIntent(wrapperArgs, nativeArgs)", Occurrence: 0}, TestName: "TestResumeElevationRefusals", EntryPoint: "ElevateResumeIntent"},
		{Site: Site{File: "resume.go", Function: "ValidateResumeIntent", Guard: "if intent.Identity != nil", Return: "return &ResumeInvalidError{Reason: \"identity on new or latest\"}", Occurrence: 0}, TestName: "TestResumeIntentValidation", EntryPoint: "ValidateResumeIntent"},
		{Site: Site{File: "resume.go", Function: "ValidateResumeIntent", Guard: "if intent.Identity == nil", Return: "return &ResumeInvalidError{Reason: \"missing identity\"}", Occurrence: 0}, TestName: "TestResumeIntentValidation", EntryPoint: "ValidateResumeIntent"},
		{Site: Site{File: "resume.go", Function: "ValidateResumeIntent", Guard: "if identity == \"latest\" || identity == \"last\" || identity == \"--last\"", Return: "return &ResumeInvalidError{Reason: \"picker identity\"}", Occurrence: 0}, TestName: "TestResumeIntentValidation", EntryPoint: "ValidateResumeIntent"},
		{Site: Site{File: "resume.go", Function: "ValidateResumeIntent", Guard: "if !valid", Return: "return &ResumeInvalidError{Reason: \"invalid identity or provider kind\"}", Occurrence: 0}, TestName: "TestResumeIntentValidation", EntryPoint: "ValidateResumeIntent"},
		{Site: Site{File: "resume.go", Function: "ResolveResumeSelectors", Guard: "switch <expression> case default", Return: "return ResumeElevation{}, &ResumeInvalidError{Reason: \"invalid wrapper selector\"}", Occurrence: 0}, TestName: "TestResumeElevationRefusals", EntryPoint: "ElevateResumeIntent"},
		{Site: Site{File: "resume.go", Function: "ResolveResumeSelectors", Guard: "if len(selections) > 1", Return: "return ResumeElevation{}, &ResumeInvalidError{Reason: \"conflicting selectors\"}", Occurrence: 0}, TestName: "TestResumeElevationRefusals", EntryPoint: "ElevateResumeIntent"},
		{Site: Site{File: "resume.go", Function: "ResolveResumeSelectors", Guard: "if err != nil", Return: "return ResumeElevation{}, err", Occurrence: 0}, TestName: "TestResumeElevationRefusals", EntryPoint: "ElevateResumeIntent"},
		{Site: Site{File: "systems/claude/restart.go", Function: "System.ExportRestartTemplate", Guard: "if err != nil", Return: "return RestartTemplate{}, err", Occurrence: 0}, TestName: "TestClaudeRestartTemplateRefusals", EntryPoint: "ExportRestartTemplate"},
		{Site: Site{File: "systems/claude/restart.go", Function: "System.ValidateRestartTransformation", Guard: "if template.Schema != RestartSchema || template.SchemaVersion != RestartSchemaVersion", Return: "return &RestartInvalidError{Reason: \"unsupported restart schema\"}", Occurrence: 0}, TestName: "TestClaudeRestartTemplateRefusals", EntryPoint: "ValidateRestartTransformation"},
		{Site: Site{File: "systems/claude/restart.go", Function: "System.ValidateRestartTransformation", Guard: "if template.Data.Argv == nil || slot.Flag != resumeFlag || slot.Index < 0 || slot.Index > len(template.Data.Argv)", Return: "return &RestartInvalidError{Reason: \"invalid identity slot\"}", Occurrence: 0}, TestName: "TestClaudeRestartTemplateRefusals", EntryPoint: "ValidateRestartTransformation"},
		{Site: Site{File: "systems/claude/restart.go", Function: "System.ValidateRestartTransformation", Guard: "if err != nil", Return: "return err", Occurrence: 0}, TestName: "TestClaudeRestartTemplateRefusals", EntryPoint: "ValidateRestartTransformation"},
		{Site: Site{File: "systems/claude/restart.go", Function: "System.ValidateRestartTransformation", Guard: "if elevated.Intent.Kind != agentic.ResumeNew || !slices.Equal(elevated.NativeArgs, template.Data.Argv)", Return: "return &RestartInvalidError{Reason: \"selector left in restart argv\"}", Occurrence: 0}, TestName: "TestClaudeRestartTemplateRefusals", EntryPoint: "ValidateRestartTransformation"},
		{Site: Site{File: "systems/claude/restart.go", Function: "System.ValidateRestartTransformation", Guard: "if err != nil", Return: "return err", Occurrence: 1}, TestName: "TestClaudeRestartTemplateRefusals", EntryPoint: "ValidateRestartTransformation"},
		{Site: Site{File: "systems/claude/restart.go", Function: "System.ValidateRestartTransformation", Guard: "if !slices.Equal(expected, argv)", Return: "return &RestartInvalidError{Reason: \"not the exact one-insertion transformation\"}", Occurrence: 0}, TestName: "TestClaudeRestartExactInsertion", EntryPoint: "ValidateRestartTransformation"},
		{Site: Site{File: "systems/claude/restart.go", Function: "System.ValidateRestartTransformation", Guard: "if !bound", Return: "return &RestartInvalidError{Reason: \"identity insertion is not a native selector\"}", Occurrence: 0}, TestName: "TestClaudeRestartTemplateRefusals", EntryPoint: "ValidateRestartTransformation"},
		{Site: Site{File: "systems/claude/resume.go", Function: "System.ElevateResumeIntent", Guard: "if !known", Return: "return agentic.ResumeElevation{}, &agentic.ResumeInvalidError{Reason: \"unknown option arity\"}", Occurrence: 0}, TestName: "TestResumeElevationRefusals", EntryPoint: "ElevateResumeIntent"},
		{Site: Site{File: "systems/claude/resume.go", Function: "System.ElevateResumeIntent", Guard: "if option.name == \"--session-id\" || option.name == \"--fork-session\"", Return: "return agentic.ResumeElevation{}, &agentic.ResumeInvalidError{Reason: \"ambiguous native identity\"}", Occurrence: 0}, TestName: "TestResumeElevationRefusals", EntryPoint: "ElevateResumeIntent"},
		{Site: Site{File: "systems/claude/resume.go", Function: "System.ElevateResumeIntent", Guard: "if !strings.HasPrefix(native[option.index], \"--\") && len(native[option.index]) > 2 && !strings.HasPrefix(native[option.index], \"-r\")", Return: "return agentic.ResumeElevation{}, &agentic.ResumeInvalidError{Reason: \"combined short selector\"}", Occurrence: 0}, TestName: "TestResumeElevationRefusals", EntryPoint: "ElevateResumeIntent"},
		{Site: Site{File: "systems/claude/resume.go", Function: "System.ElevateResumeIntent", Guard: "if len(option.values) != 1", Return: "return agentic.ResumeElevation{}, &agentic.ResumeInvalidError{Reason: \"picker selector\"}", Occurrence: 0}, TestName: "TestResumeElevationRefusals", EntryPoint: "ElevateResumeIntent"},
		{Site: Site{File: "systems/claude/resume.go", Function: "System.ElevateResumeIntent", Guard: "unconditional", Return: "return agentic.ResolveResumeSelectors(wrapper, selections, tail, agentic.ResumeClaudeUUID)", Occurrence: 0}, TestName: "TestResumeElevationRefusals", EntryPoint: "ElevateResumeIntent"},
		{Site: Site{File: "systems/codex/resume.go", Function: "System.ElevateResumeIntent", Guard: "unconditional", Return: "return elevateResume(wrapper, native)", Occurrence: 0}, TestName: "TestResumeElevationRefusals", EntryPoint: "ElevateResumeIntent"},
		{Site: Site{File: "systems/codex/resume.go", Function: "elevateResume", Guard: "if i+1 >= len(native) || strings.HasPrefix(native[i+1], \"-\")", Return: "return agentic.ResumeElevation{}, &agentic.ResumeInvalidError{Reason: \"picker selector\"}", Occurrence: 0}, TestName: "TestResumeElevationRefusals", EntryPoint: "ElevateResumeIntent"},
		{Site: Site{File: "systems/codex/resume.go", Function: "elevateResume", Guard: "if separated", Return: "return agentic.ResumeElevation{}, &agentic.ResumeInvalidError{Reason: \"surplus positional\"}", Occurrence: 0}, TestName: "TestResumePositionalCardinality", EntryPoint: "ElevateResumeIntent"},
		{Site: Site{File: "systems/codex/resume.go", Function: "elevateResume", Guard: "if strings.HasPrefix(token, \"-\") && !knownBoolean", Return: "return agentic.ResumeElevation{}, &agentic.ResumeInvalidError{Reason: \"unknown option arity\"}", Occurrence: 0}, TestName: "TestResumeElevationRefusals", EntryPoint: "ElevateResumeIntent"},
		{Site: Site{File: "systems/codex/resume.go", Function: "elevateResume", Guard: "if promptBound", Return: "return agentic.ResumeElevation{}, &agentic.ResumeInvalidError{Reason: \"surplus positional\"}", Occurrence: 0}, TestName: "TestResumePositionalCardinality", EntryPoint: "ElevateResumeIntent"},
		{Site: Site{File: "systems/codex/resume.go", Function: "elevateResume", Guard: "if waiting", Return: "return agentic.ResumeElevation{}, &agentic.ResumeInvalidError{Reason: \"picker selector\"}", Occurrence: 0}, TestName: "TestResumeElevationRefusals", EntryPoint: "ElevateResumeIntent"},
		{Site: Site{File: "systems/codex/resume.go", Function: "elevateResume", Guard: "unconditional", Return: "return agentic.ResolveResumeSelectors(wrapper, selections, tail, agentic.ResumeCodexThread)", Occurrence: 0}, TestName: "TestResumeElevationRefusals", EntryPoint: "ElevateResumeIntent"},
		{Site: Site{File: "systems/muse/resume.go", Function: "System.ElevateResumeIntent", Guard: "if separated", Return: "return agentic.ResumeElevation{}, &agentic.ResumeInvalidError{Reason: \"surplus positional\"}", Occurrence: 0}, TestName: "TestResumePositionalCardinality", EntryPoint: "ElevateResumeIntent"},
		{Site: Site{File: "systems/muse/resume.go", Function: "System.ElevateResumeIntent", Guard: "if strings.HasPrefix(token, \"-\") && !museResumeBooleans[name]", Return: "return agentic.ResumeElevation{}, &agentic.ResumeInvalidError{Reason: \"unknown option arity\"}", Occurrence: 0}, TestName: "TestResumeElevationRefusals", EntryPoint: "ElevateResumeIntent"},
		{Site: Site{File: "systems/muse/resume.go", Function: "System.ElevateResumeIntent", Guard: "if command", Return: "return agentic.ResumeElevation{}, &agentic.ResumeInvalidError{Reason: \"surplus positional\"}", Occurrence: 0}, TestName: "TestResumePositionalCardinality", EntryPoint: "ElevateResumeIntent"},
		{Site: Site{File: "systems/muse/resume.go", Function: "System.ElevateResumeIntent", Guard: "if waiting", Return: "return agentic.ResumeElevation{}, &agentic.ResumeInvalidError{Reason: \"picker selector\"}", Occurrence: 0}, TestName: "TestResumeElevationRefusals", EntryPoint: "ElevateResumeIntent"},
		{Site: Site{File: "systems/muse/resume.go", Function: "System.ElevateResumeIntent", Guard: "unconditional", Return: "return agentic.ResolveResumeSelectors(wrapper, selections, tail, agentic.ResumeMuseSession)", Occurrence: 0}, TestName: "TestResumeElevationRefusals", EntryPoint: "ElevateResumeIntent"},
		{Site: Site{File: "systems/claude/resume.go", Function: "System.ElevateResumeIntent", Guard: "if arity == optionNone && strings.HasPrefix(native[option.index], \"--\") && strings.Contains(native[option.index], \"=\")", Return: "return agentic.ResumeElevation{}, &agentic.ResumeInvalidError{Reason: \"attached value on boolean option\"}", Occurrence: 0}, TestName: "TestResumeAttachedOptionInventory", EntryPoint: "ElevateResumeIntent"},
		{Site: Site{File: "systems/codex/resume.go", Function: "elevateResume", Guard: "if attached && knownBoolean", Return: "return agentic.ResumeElevation{}, &agentic.ResumeInvalidError{Reason: \"attached value on boolean option\"}", Occurrence: 0}, TestName: "TestResumeAttachedOptionInventory", EntryPoint: "ElevateResumeIntent"},
		{Site: Site{File: "systems/muse/resume.go", Function: "System.ElevateResumeIntent", Guard: "if attached && museResumeBooleans[name]", Return: "return agentic.ResumeElevation{}, &agentic.ResumeInvalidError{Reason: \"attached value on boolean option\"}", Occurrence: 0}, TestName: "TestResumeAttachedOptionInventory", EntryPoint: "ElevateResumeIntent"},
	}
}
